### ISSUE TITLE
7 errors

### ISSUE THREAD

**Issue by corywangjiazheng** [fthgrsy27/Cuisiner#1]
<img width="1250" alt="2023-03-14 23 57 51" src="https://user-images.githubusercontent.com/123780321/225168268-9ce590c5-ab2c-403d-a699-330fa53be63e.png">

Hi, could you help me how to fix these errors? Thanks so much!

**Comment by fatih-gursoy** [comment]
Did you run 'pod install' ?

**Comment by corywangjiazheng** [comment]
Sorry, I try to find a way to run ""pod install", but I cannot fint it. I have no idea how to run 'pod install'.

**Comment by fatih-gursoy** [comment]
go to project folder in Terminal and type "pod install" https://stackoverflow.com/a/30418586/5979815

**Comment by corywangjiazheng** [comment]
My step 7: "Now type pod install. Wait for that to finish. It could take a while" is not work.
shows zsh: command not found: pod

Thanks

**Comment by fatih-gursoy** [comment]
Password? I guess, it is your mac password to install cocoapods in terminal. I think you should learn more about cocoapods and iOS development.

**Comment by corywangjiazheng** [comment]
Sorry, I'm a beginner, so sorry to bother you.

**Comment by fatih-gursoy** [comment]
No problem about that. There are lots of sources about this issue. After learning it, i think you can do it properly.
